# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx-zoo:
        container_name: nginx-zoo
        # используем последний стабильный образ nginx
        build: ./images/nginx
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./etc:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        # nginx использует php для обработки запросов, поэтому запускается после него
        depends_on:
            - composer-zoo
        links:
            - php-zoo

    php-zoo:
        container_name: php-zoo
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www

    composer-zoo:
        container_name: composer-zoo
        build: ./images/composer
        volumes:
            - ./www:/var/www
        tty: true
        depends_on:
            - php-zoo